workspace("simile")
    configurations({
        "Debug",
        "Release"
    })

project("simile")
    kind("StaticLib")
    language("C++")
    targetdir("bin/%{cfg.buildcfg}")
    libdirs({
        "./libs/**"
    })
    includedirs({
        "./inc/"
    })
    links({
        "spdlog"
    })
    files({
        "./inc/**.hpp",
        "./src/**.cpp"
    })
    defines({
        "PROJECT_ROOT_DIR=%{prj.location}"
    })
    filter("system:not windows")
        defines({
            "NOT_WINDOWS"
        })
    filter("configurations:Debug")
        defines({
            "DEBUG"
        })
        symbols("On")
        postbuildcommands({
            "doxygen"
        })
    filter({ "system:linux", "configurations:Debug", "action:gmake or action:gmake2" })
        buildoptions({
            "-fprofile-arcs",
            "-ftest-coverage"
        })
        linkoptions({
            "-lgcov",
            "--coverage"
        })
    filter("configurations:Release")
        defines({
            "NDEBUG"
        })
        optimize("On")

project("SimileTests")
    kind("ConsoleApp")
    language("C++")
    targetdir("test/bin/%{cfg.buildcfg}")
    objdir("./test/obj")
    libdirs({
        "./libs/**"
    })
    includedirs({
    })
    links({
        "criterion"
    })
    files({
        "./test/inc/**.hpp",
        "./test/src/**.cpp"
    })
    postbuildcommands({
        "%{cfg.buildtarget.relpath}"
    })
    defines({
        "PROJECT_ROOT_DIR=\"%{cfg.buildtarget.directory}/../..\""
    })
    filter({ "system:linux", "action:gmake or action:gmake2" })
        postbuildcommands({
            "gcovr"
        })
        buildoptions({
            "-fprofile-arcs",
            "-ftest-coverage"
        })
        linkoptions({
            "-lgcov",
            "--coverage"
        })

