workspace("simile")
    configurations({
        "Debug",
        "Release"
    })

project("simile")
    kind("StaticLib")
    language("C")
    cdialect("C11")
    targetdir("bin/%{cfg.buildcfg}")
    libdirs({
        "./libs/**"
    })
    includedirs({
        "./libs/glad/inc/",
        "./libs/glfw/include/",
        "./libs/libcyaml/include/",
        "./libs/base64/inc/"
    })
    links({
        "m",
        "gl",
        "glfw3",
        "cyaml",
        "yaml"
    })
    files({
        "./libs/glad/src/**.c",
        "./libs/base64/src/**.c",
        "./inc/**.h",
        "./src/**.c"
    })
    defines({
        "PROJECT_ROOT_DIR=%{prj.location}"
    })
    filter("system:not windows")
        defines({
            "NOT_WINDOWS"
        })
    filter("configurations:Debug")
        defines({
            "DEBUG"
        })
        symbols("On")
        postbuildcommands({
            "doxygen"
        })
    filter({ "system:linux", "configurations:Debug", "action:gmake or action:gmake2" })
        buildoptions({
            "-fprofile-arcs",
            "-ftest-coverage"
        })
        linkoptions({
            "-lgcov",
            "--coverage"
        })
    filter("configurations:Release")
        defines({
            "NDEBUG"
        })
        optimize("On")

project("SimileTests")
    kind("ConsoleApp")
    language("C")
    cdialect("C11")
    targetdir("test/bin/%{cfg.buildcfg}")
    objdir("./test/obj")
    libdirs({
        "./libs/**"
    })
    includedirs({
        "./libs/glad/inc",
        "./libs/glfw/include",
        "./libs/libcyaml/include/",
        "./libs/base64/inc/"
    })
    links({
        "m",
        "criterion",
        "simile",
        "glfw3",
        "cyaml",
        "yaml"
    })
    files({
        "./test/inc/**.h",
        "./test/src/**.c"
    })
    postbuildcommands({
        "%{cfg.buildtarget.relpath}"
    })
    defines({
        "PROJECT_ROOT_DIR=\"%{cfg.buildtarget.directory}/../..\""
    })
    filter({ "system:linux", "action:gmake or action:gmake2" })
        postbuildcommands({
            "gcovr"
        })
        buildoptions({
            "-fprofile-arcs",
            "-ftest-coverage"
        })
        linkoptions({
            "-lgcov",
            "--coverage"
        })

